package model

import com.fasterxml.jackson.annotation.JsonProperty

/**
  * Created by pragya.mishra on 11/23/17.
  *
  * A class to represent payment request from merchant
  * with mapping of keys with "_" to their camelCase version
  */

case class PaymentRequest (
    @JsonProperty var key : String,
    @JsonProperty var txnid : String,
    @JsonProperty var version : String,
    @JsonProperty("api_version") var apiVersion : String,
    @JsonProperty("pre_init_mode") var preInitMode: String,
    @JsonProperty var amount : String,
    @JsonProperty("additional_charges") var additionalCharges : String,
    @JsonProperty var firstname : String,
    @JsonProperty("salt_version") var saltVersion : String,
    @JsonProperty var email : String,
    @JsonProperty var phone : String,
    @JsonProperty var productinfo : String,
    @JsonProperty("user_credentials") var userCredentials : String,
    @JsonProperty var surl : String,
    @JsonProperty var furl : String,
    @JsonProperty var notifyurl : String,
    @JsonProperty var codurl : String,
    @JsonProperty var miles : String,
    @JsonProperty var pubkey : String,
    @JsonProperty var lastname : String,
    @JsonProperty var address1 : String,
    @JsonProperty var address2 : String,
    @JsonProperty("shipping_firstname") var shippingFirstname : String,
    @JsonProperty("shipping_lastname") var shippingLastname : String,
    @JsonProperty("shipping_address1") var shippingAddress1 : String,
    @JsonProperty("shipping_address2") var shippingAddress2 : String,
    @JsonProperty("shipping_city") var shippingCity : String,
    @JsonProperty("shipping_state") var shippingState : String,
    @JsonProperty("shipping_country") var shippingCountry : String,
    @JsonProperty("shipping_zipcode") var shippingZipcode : String,
    @JsonProperty("shipping_phone") var shippingPhone : String,
    @JsonProperty var city : String,
    @JsonProperty var state : String,
    @JsonProperty var country : String,
    @JsonProperty var zipcode : String,
    @JsonProperty var nsc : String,
    @JsonProperty("enforce_paymethod") var enforcePaymethod : String,
    @JsonProperty("drop_category") var dropCategory : String,
    @JsonProperty("offer_key") var offerKey : String,
    @JsonProperty("service_provider") var serviceProvider : String,
    @JsonProperty("note_category") var noteCategory : String,
    @JsonProperty("custom_note") var customNote : String,
    @JsonProperty var udf1 : String,
    @JsonProperty var udf2 : String,
    @JsonProperty var udf3 : String,
    @JsonProperty var udf4 : String,
    @JsonProperty var udf5 : String,
    @JsonProperty var udf6 : String,
    @JsonProperty("base_payuid") var basePayuid : String,
    @JsonProperty("base_merchantid") var baseMerchantid : String,
    @JsonProperty("vendor_id") var vendorId : String,
    @JsonProperty var si : String,
    @JsonProperty("force_pgid") var forcePgid : String,
    @JsonProperty("paisa_mecode") var paisaMecode : String,
    @JsonProperty("device_type") var deviceType : String,
    @JsonProperty("instrument_type") var instrumentType : String,
    @JsonProperty("instrument_id") var instrumentId : String,
    @JsonProperty var ismobileview : String,
    @JsonProperty("card_merchant_param") var cardMerchantParam : String,
    @JsonProperty("one_click_checkout") var oneClickCheckout : String,
    @JsonProperty("retry_payuids") var retryPayuids : String,
    @JsonProperty var html : String,
    @JsonProperty var sdktoken : String,
    @JsonProperty var pg : String,
    @JsonProperty var bankcode : String,
    @JsonProperty var ccnum : String,
    @JsonProperty var ccname : String,
    @JsonProperty var ccvv : String,
    @JsonProperty var ccexpmon : String,
    @JsonProperty var ccexpyr : String,
    @JsonProperty var otp : String,
    @JsonProperty("store_card_token") var storeCardToken : String,
    @JsonProperty("store_card") var storeCard : String,
    @JsonProperty("card_name") var cardName : String,
    @JsonProperty("is_atm_pin") var isAtmPin : String,
    @JsonProperty var hash : String
    ) {
}
