package consts

/**
  * Created by pragya.mishra on 11/23/17.
  */

case class PaymentRequest ( var key : Option[String],
                           var txnid : Option[String],
                           var version : Option[String],
                           var api_version : Option[String],
                           var pre_init_mode: Option[String],
                           var amount : Option[String],
                           var additional_charges : Option[String],
                           var firstname : Option[String],
                           var salt_version : Option[String],
                           var email : Option[String],
                           var phone : Option[String],
                           var productinfo : Option[String],
                           var user_credentials : Option[String],
                           var surl : Option[String],
                           var furl : Option[String],
                           var notifyurl : Option[String],
                           var codurl : Option[String],
                           var miles : Option[String],
                           var pubkey : Option[String],
                           var lastname : Option[String],
                           var address1 : Option[String],
                           var address2 : Option[String],
                           var shipping_firstname : Option[String],
                           var shipping_lastname : Option[String],
                           var shipping_address1 : Option[String],
                           var shipping_address2 : Option[String],
                           var shipping_city : Option[String],
                           var shipping_state : Option[String],
                           var shipping_country : Option[String],
                           var shipping_zipcode : Option[String],
                           var shipping_phone : Option[String],
                           var city : Option[String],
                           var state : Option[String],
                           var country : Option[String],
                           var zipcode : Option[String],
                           var nsc : Option[String],
                           var enforce_paymethod : Option[String],
                           var drop_category : Option[String],
                           var offer_key : Option[String],
                           var service_provider : Option[String],
                           var note_category : Option[String],
                           var custom_note : Option[String],
                           var udf1 : Option[String],
                           var udf2 : Option[String],
                           var udf3 : Option[String],
                           var udf4 : Option[String],
                           var udf5 : Option[String],
                           var udf6 : Option[String],
                           var base_payuid : Option[String],
                           var base_merchantid : Option[String],
                           var vendor_id : Option[String],
                           var si : Option[String],
                           var force_pgid : Option[String],
                           var paisa_mecode : Option[String],
                           var device_type : Option[String],
                           var instrument_type : Option[String],
                           var instrument_id : Option[String],
                           var ismobileview : Option[String],
                           var card_merchant_param : Option[String],
                           var one_click_checkout : Option[String],
                           var retry_payuids : Option[String],
                           var html : Option[String],
                           var sdktoken : Option[String],
                           var pg : Option[String],
                           var bankcode : Option[String],
                           var ccnum : Option[String],
                           var ccname : Option[String],
                           var ccvv : Option[String],
                           var ccexpmon : Option[String],
                           var ccexpyr : Option[String],
                           var otp : Option[String],
                           var store_card_token : Option[String],
                           var store_card : Option[String],
                           var card_name : Option[String],
                           var is_atm_pin : Option[String],
                           var hash : Option[String]
                         ) {

}


